### PR TITLE
Bania's just created new branch

### PR DESCRIPTION
**Pull request by nlauchande**

### CODE REVIEW

**Comment by BaniaFonseca** [comment]
We are no longer using this branch, I've created a new one named dev  ...

**Comment by BaniaFonseca** [comment]
so please can you close this pull request? Because I need to delete this branch

**Comment by BaniaFonseca** [comment]
the development team can push and pull to  branch dev, without restrictions, but, they can merge it to main branch only via pull request ...

**Comment by tjiagoM** [comment]
@BaniaFonseca closed, go ahead and do your thing :)

**Pull request closed without merging**
